# docker build -t soteria-win64 .

FROM debian:11

LABEL maintainer="Random"

LABEL version="1.0.8"

LABEL description="Soteria 1.0.8 | Docker for windows x64"

ARG DEBIAN_FRONTEND=nointeractive

RUN apt update

RUN apt-get install -y git unzip curl wget

WORKDIR /root

RUN git clone https://github.com/Soteria-Network/Soteria.git

WORKDIR /root/Soteria

RUN scripts/00-install-deps.sh windows

WORKDIR /root/Soteria/depends

RUN make HOST=x86_64-w64-mingw32 -j4

WORKDIR /root/Soteria

RUN ./autogen.sh

RUN contrib/install_db4.sh ../

RUN export BDB_PREFIX=/root/db4

RUN CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-5.3" BDB_CFLAGS="-I${BDB_PREFIX}/include" --prefix=/ --disable-shared --disable-tests --disable-gui-tests --disable-man

RUN make -j4

CMD ["tail", "-f", "/dev/null"]
