#ifndef SOTERIA_CHAINPARAMSSEEDS_H
#define SOTERIA_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the soteria network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0,0,0,0,0,0,0,0,0,0,0xff,0xff,51,75,75,88}, 8323},
    {{0x20,0x01,0x04,0x1d,0x07,0x01,0x11,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x85,0x2d}, 8323},
    {{0,0,0,0,0,0,0,0,0,0,0xff,0xff,178,72,89,199}, 8323},
    {{0,0,0,0,0,0,0,0,0,0,0xff,0xff,57,129,45,4}, 8323}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // SOTERIA_CHAINPARAMSSEEDS_H
