name: soteria-core
# Running 'snapcraft register <name>' is advised
version: '1.0.0'
summary: Reference client of Soteria, a peer-to-peer digital currency like Bitcoin.
description: |
  Soteria is a modern POW cryptocurrency that was inspired by BTC & RVN and what we think what it should be a modern POW that can be mined by CPU & GPU which contain all the latest technological advances in its codebase. The Soteria Core software allows anyone to operate a node in the Soteria blockchain networks and uses the 2 new hashing methods for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core18
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: i386
    run-on: i386

apps:
  d:
    command: soteriad
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/soteria-core/common/.soteria/ instead of ~/snap/soteria-core/current/.soteria/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch soteria-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: soteria-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: soteria-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: test_soteria
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is udsable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  soteria-core:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/soteria-network/soteria/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but soteria designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/soteria-network/soteria/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/soteria-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/soteria-network/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum soteria-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep soteria-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf soteria-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/test_soteria); then
        echo "Soteria tests failed."
        return
      else
        echo "Soteria tests passed."
      fi
      wget https://raw.githubusercontent.com/soteria-network/soteria/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing Soteria Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/soteriad
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official soteria-qt build on arm64
        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/soteria-qt
      fi
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/soteria-cli
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/soteria-tx
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin soteria-${SNAPCRAFT_PROJECT_VERSION}/bin/test_soteria
      wget https://raw.githubusercontent.com/soteria/soteria/master/share/pixmaps/soteria128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps soteria128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
